runtime: python310

instance_class: F2

env_variables:
  DEPLOYMENT_ENV: "production"

handlers:
- url: /assets
  static_dir: assets

- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 1
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic
